### ISSUE TITLE
Refactor various tests

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1017]
```[tasklist]
### Tasks
- [x] unit/test_equation_system.py
- [x] unit/test_parameters.py
- [ ] https://github.com/pmgbergen/porepy/issues/1018
- [ ] https://github.com/pmgbergen/porepy/issues/1019
- [ ] https://github.com/pmgbergen/porepy/issues/1020
```
