### ISSUE TITLE
Delete outdated non-conforming functionality

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1033]
```[tasklist]
### Tasks
- [ ] fracs.nonconforming.py
- [ ] tests.integration.test_DFN.py
- [ ] tests.unit.test_merging_nonconforming_grids.py
```

**Comment by keileg** [comment]
Should have no dependencies, upstream of downstream.
