### ISSUE TITLE
Deleted do-almost-nothing discretizations related to the assembler

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1035]
```[tasklist]
### Tasks
- [x] numerics.discretization.py ONLY class VoidDiscretization
- [x] numerics.interface_laws.cell_dof_face_dof_map.py
- [x] numerics.fv.fv_elliptic.py ONLY class EllipticDiscretizationZeroPermeability
```

**Comment by keileg** [comment]
Should have no dependencies

**Comment by IvarStefansson** [comment]
CellDofFaceDofMap is used in test_DFN

**Comment by keileg** [comment]
This is a dependency on #1033 which I failed to catch.

**Comment by IvarStefansson** [comment]
But that should be fine as long as we merge into deletion branch, not directly to develop, right?

**Comment by keileg** [comment]
Yes
