### ISSUE TITLE
Delete single phase flow tests based on the assembler

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1036]
```[tasklist]
### Tasks
- [x] tests.unit.test_darcy_mortar.py
- [x] tests.integration.test_vem_convergence.py
- [x] tests.integration.test_tpfaMonoCoupling
```

**Comment by keileg** [comment]
This must be done before the assembler can be deleted.
