### ISSUE TITLE
Delete interface_laws

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1040]
```[tasklist]
### Tasks
- [x] numerics.interface_laws.elliptic_interface_laws.py: RobinCoupling: See comment below
- [x] numerics.interface_laws.elliptic_interface_laws.py: Class FluxPressureContinuity
- [x] numerics.interface_laws.elliptic_interface_laws.py: Class WellCoupling
- [x] numerics.interface_laws.hyperbolic_interface_laws: See comment below
```

**Comment by keileg** [comment]
The RobinCoupling and UpwindCoupling classes will need to keep their methods `discretize()` (at least for now, perhaps we can do something smarter here at a later time) to stay compatible with the Ad framework, but all methods `assemble_*` can go.

**Comment by keileg** [comment]
@IvarStefansson Please confirm that the class [WellCoupling](https://github.com/pmgbergen/porepy/blob/a7a3058cdf84252fc7383dd4b1a9010dea0043ff/src/porepy/numerics/interface_laws/elliptic_interface_laws.py#L928) can be deleted.

**Comment by keileg** [comment]
This must be done after #1036

**Comment by IvarStefansson** [comment]
And do we need RobinCoupling.discretize?

**Comment by IvarStefansson** [comment]
Should we delete AbstractInterfaceLaw as well? It doesn't really make sense to define a contract for a single class (UpwindCoupling)

**Comment by keileg** [comment]
I will delete AbstractInterfaceLaw
