### ISSUE TITLE
Delete the Assembler, DofManager

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1041]
```[tasklist]
### Tasks
- [ ] numerics.mixed_dim.assembler.py
- [ ] numerics.mixed_dim.assembler_filter.py
- [ ] numerics.mixed_dim.dof_manager.py
- [ ] tests.unit.test_assembler.py
- [ ] tests.unit.test_dof_manager.py
```

**Comment by keileg** [comment]
Depends on #1036, possibly more.
