### ISSUE TITLE
Purge test folders

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#1056]
```[tasklist]
### Tasks
- [ ] Move or delete any remaining tests in unit and integration
- [ ] Move any utility functionality to be kept from unit, integration and common (to applications)
- [ ] Delete remaining utility code
- [ ] Purge folders tests.unit and tests.integration
```

**Comment by keileg** [comment]
Resolved by #1061
