### ISSUE TITLE
Numerical parameters

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#1150]
We might want to collect numerical parameters in some dedicated object, possibly of the `MaterialConstants` type. @keileg's comments copied from other discussion:

Agree! I can think of a few reasons for revisiting this:

1. Cleanliness.
2. Getting an overview of such numerical parameters in use.
3. (hopefully) introduce scaling of numerical parameters, just as with physical ones.

**Comment by IvarStefansson** [comment]
Note that this may affect both model parameters and solver parameters as defined in #1210.

**Comment by jwboth** [comment]
Task: Map out "all" numerical constant which are potentially in use. Provide a new object (my suggestion would be to follow the naming style and use `NumericalConstants`) - check out models/material_constants.py as well. In the process, we will determine how subclasses can be designed to better indicate the thematic grouping of constants. The priority for the first should be the two reasons mentioned by Ivar. Scaling will follow in a second step.

**Comment by isakhammer** [comment]
# Work in progress of Overview of Potential Parameters classes PorePy  

Below is a list of parameters that are less frequently used but could be valuable to incorporate into the class.

1. **Where and what these parameters are used**  
   (Based on the source code)

2. **How these parameters are tested**  
   (Based on the testing framework, tutorials and run scripts)

#### Suggestions from Eirik:
- Search for `tol` to identify various tolerance parameters across different contexts.
- Maintain a high-level overview; avoid going too deep into specific cases.


### Candidates for contact mechanics 
**Todo**


### Newton solver
**Todo**

### Physical parameters 
**Todo**


### Candidates for mesh arguments og grids
**Todo**

1. [test_refinement 1](https://github.com/pmgbergen/porepy/blob/e10aeaa351181b9a71b6e890a50b32484386d8b6/tests/grids/test_refinement.py#L379)
    ```python
    mesh_args = {"mesh_size_frac": 1, "mesh_size_bound": 1, "mesh_size_min": 0.1}
    num_ref = 3
    params = {
        "mode": "nested",
        "num_refinements": num_ref,
        "mesh_param": mesh_args,
    }
    
    
        params = {
        "mode": "nested",
        "num_refinements": num_ref,
        "mesh_param": mesh_args,
        # The fracture is a constraint
        "grid_param": {"constraints": np.array([0])},
    }

    ```


2. [test_mdg_generation](https://github.com/pmgbergen/porepy/blob/e10aeaa351181b9a71b6e890a50b32484386d8b6/tests/grids/test_mdg_generation.py#L90C1-L115C10)
    ```python

        def lower_level_extra_args_data_2d(self) -> List[dict]:
        """Admissible keys for 2d cases"""
        simplex_extra_args: dict = {
            "mesh_size_min": 0.5,
            "mesh_size_bound": 1.0,
            "mesh_size_frac": 0.5,
        }
        cartesian_extra_args: dict = {"nx": [10, 10], "physdims": [5, 5]}
        tensor_grid_extra_args: dict = {
            "x": np.array([0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]),
            "y": np.array([0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]),
        }
       ...

    def higher_level_extra_args_data_3d(self) -> List[dict]:
        """Admissible keys in pp.create_mdg for 3d cases"""
        simplex_extra_args: dict = {
            "cell_size_min": 0.5,
            "cell_size_boundary": 1.0,
            "cell_size_fracture": 0.5,
        }
        cartesian_extra_args: dict = {
            "cell_size_x": 0.5,
            "cell_size_y": 0.5,
            "cell_size_z": 0.5,
        }
        
         ```


3.  [test_mdg_generation 2](https://github.com/pmgbergen/porepy/blob/e10aeaa351181b9a71b6e890a50b32484386d8b6/tests/grids/test_mdg_generation.py#L450C5-L456C10)
        
 ```python
            cell_size_args = ["cell_size", "cell_size_x", "cell_size_y", "cell_size_z"]
        meshing_args: dict = {
            "cell_size": 0.1,
            "cell_size_x": 0.1,
            "cell_size_y": 0.1,
            "cell_size_z": 0.1,
        }

 ```

**Comment by jwboth** [comment]
Identified tasks during discussion:
- [ ] Introduce object for collecting numerical tuning parameters.
- [ ] Move contact mechanics related parameters in the object.
- [ ] Adapt the code base to the changes.
- [ ] Decide where the new object will be put.
