### ISSUE TITLE
Test scaling

### ISSUE THREAD

**Issue by IngridKJ** [pmgbergen/porepy#1156]
Use nontrivial values for testing the scaling in models. Also make sure to have nontrivial solutions where the scaling is tested (e.g. fluid mass balance had a zero-solution). 
Note: All tests pass now, except test_energy_balance which refuses to converge.

```[tasklist]
### Tasks
- [x] test_thermoporomechanics
- [x] test_poromechanics
- [x] test_momentum_balance
- [x] test_fluid_mass_balance
- [ ] test_energy_balance
```
