### ISSUE TITLE
Reimplementation of Ad projection operators

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1182]

**Comment by keileg** [comment]
Some of the functionality in `po.models.geometry` may also be suited for this approach.

**Comment by IvarStefansson** [comment]
> Some of the functionality in `po.models.geometry` may also be suited for this approach.

That's an interesting comment. Is there any chance this approach can help us with representation of tensors and their products?

**Comment by keileg** [comment]
Perhaps, it depends on what you mean. I suggest we discuss in person.

**Comment by keileg** [comment]
Implementing this will require three main steps, each split into separate tasks.

## Preparatory steps

```[tasklist]
### Task 
- [ ] Improve test coverage for the Ad version of the projections, in particular the mortar projections. STATUS: PR soon ready.
- [ ] Prepare benchmarking for use in models. This is implemnted in  #1261 
```

## Implementation of the new projection operators
```[tasklist]
### Tasks
- [ ] Implement a first version of the RestrictionSlicer and ProjectionSlicer, outlined above. There are several suggestions for how to implement `__matmul__`, we probably should investigate all.
- [ ] Make some simple tests to verify the classes. Copilot should be able to handle this.
- [ ] Prepare benchmarking for the slicing operators, stand-alone (used on `np.ndarrays` and `pp.ad.AdArrays`. Hopefully, copilot can help with this. It is important to consider both small and big arrays, and slicing/prolongation to few and many of the rows. We should also test the existing implementation of multiplying with a sparse matrix.
- [ ] Try to use the benchmarking to decide which of the implementations of `__matmul__` should be used. It could be that the results are similar for some cases, in which case we either prioritize simplicity, or keep several options for a while.
```
## Inclusion of the new slicers in the Ad operator system
```[tasklist]
### Tasks
- [ ] Introduce the new slicer classes in the `SubdomainProjection`, to replace the existing projections. It could be that we need to introduce a new Ad operator to ensure delayed evaluation (the existing projections use SparseArrays), but this should be a relatively simple task.
- [ ] Introduce the new slicer classes in the Ad parsing. My feeling is we need few if any changes to the parsing in `pp.ad.Operator`, but we may need to do modifications to `pp.ad.AdArray` to let these know how to deal with the new classes (simply leave the operation to the new class by calling its `__matmul__`)
- [ ] Expand the test suite for Ad parsing to cover the new objects.
- [ ] Modify the existing test of `SubdomainProjections`. Currently this is based on the projection matrix being explicitly available, but when we only have the action of the slicer, we need to construct the matrix (multiply with one unit vector at a time, build the matrix this way).
- [ ] Benchmarking of the new results, using the full Ad framework, again with small and large arrays, small and large slices. Copilot should be able to help. Compare with the existing implementation of the `SubdomainProjection`.
- [ ] Introduce the new functionality also to the `MortarProjection`. Modify all projections, but leave out the `sign_of_mortar_side` for now.
```

**Comment by keileg** [comment]
## Benchmarking (to be updated)
Observations from benchmarking using `line_profiler` (which btw seems to have a substantial overhead with my setup, but comparing relative performance, rather than absolute numbers, should give some indications)

Running flow_benchmark_2d_case3, with a grid of 24K cells in the matrix, ~800 mortar cells
1. Substantial time is spent in the mortar projections. Less so in the subdomain projections (but this is reasonable, the physics is homogeneous between the subdomains).
2. The time spent on defining the equations (which will include the projections) is roughly equal to that of mpfa discretization. There are indications that the mortar projections take the main part of this construction, though this is not certain, given the noise in profiling.
3. Time for assembly is (for this case) considerable less than defining equations and discretizing.
4. Time for linear solve is also not that big.

Conclusion so far: It seems the projection update project can make an impact.

**Comment by IvarStefansson** [comment]
This might be a stupid question: How will the slicing work for non-matching mortar grids?

**Comment by keileg** [comment]
> This may be a stupid question: How will the slicing work for non-matching mortar grids?

It will be more complicated, involving not only slicing, but weighted sums over rows. I haven't worked out the details, but if it gets too complicated, it could be that we end up using the old solution for non-matching grids, at least until we start using these in earnest.

**Comment by keileg** [comment]
# Benchmarking of the actual slicing and reconstruction
There turned out to be two natural ways to implement these operations:
1. Operating directly on the sparse data structures as outlined in the initial posting of this issue. Referred to as 'Option 1' below'.
2. Explicitly constructing a restriction/prolongation matrix. Referred to as 'Option 2' below.

Comments:
* Option 2 is similar to what is being done now in `pp.ad.SubdomainProjections`, however, if we go for this solution, we will not rely on `sps.bmat` to construct a combined matrix for multiple subdomains, but rather concatenate indices and construct a single matrix (could be substantially faster).
* Option 1 is rather straightforward to implement for a conforming grid, but will become highly technical for non-conforming grids, where the matrix elements of the corresponding projection matrix are non-unitary. In practice, we will end up trying to implement a general matrix-matrix (or matrix-vector) product, and we can hardly expect to improve on scipy there. The reason we may improve things for conforming grids is that in this case the matrix product is in effect slicing, and this insight may be exploited.
* If we ever introduce a `PETSc` backend for the Ad operations, Option 2 may benefit from this (assuming `PETSc` speeds up calculations). Option 1 will require that we figure out how to efficiently manipulate the PETSc sparse matrix format.
* Based on inspection of the source code, both options are expected to some improvements on the current implementation of `SubdomainProjection` and significant improvements to `MortarProjection` (which is horribly inefficient).

## The benchmarks:
Two md geometries were considered:
1. The regular geometry (case 1) from the 2d flow benchmark, with 400, 24K and 2400K cells in total.
2. Case 3 from the 3d flow benchmarks, with 30K, 150K and 350K cells in total.

We test both restriction to and prolongation from each subdomain. This is representative for both subdomain and mortar projections, with the assumption that we treat the task of identifying indices to project to and from different from the task of mapping. By similar reasoning, mapping to sets of domains is also covered.

We comment below on time for initialization, and of mapping of vectors, sparse matrices and AdArrays. In Option 2, initialization entails construction of a projection matrix, while Option 1 only stores passed information during initialization. Thus the relative importance of initialization cost depends on how many times a restriction/prolongation object is used; currently this is often only once, but future caching (#1181) may change this.

## Results
Summarized as follows:
1. Generally, prolongation is more costly than restriction, reflecting the need to construct and operate on larger vectors and matrices. The difference increases with cell count.
2. Initialization is fastest with Option 1, with a cost of roughly 2-20% of that for Option 2.
3. Restricting and prolonging a vector with Option 1 takes 20-100% of the corresponding time for Option 2. For Option 1, the time for vector operations and initialization are of the same order of magnitude (though the scaling of operations is poorer than that of initialization), while for Option 2, initialization can be 1-2 orders of magnitude more costly.
4. For matrix operations, the scaling is roughly linear for Option 1, while for Option 2 it is in general slightly worse than linear. In total, the cost for Option 1 is about 20-100% of that for Option 2, with the difference increasing with matrix size. Testing on matrices with different number of nonzeros per row indicated that Option 1 can be considerably better than Option 2 in some respect (improved prolongation, no difference in behavior for restriction). The cost of initialization is negligible compared to matrix operations.
5. For Ad arrays, Option 1 takes 50-100% of the time for Option 2, with better scaling with cell count.

## Conclusions
1. Option 1 is significantly faster than Option 2, in particular for larger grids where the difference matters the most. Option 1 is therefore the preferred method.
2. The need to stay compatible with non-conforming grids means we also will need Option 2. The projection objects will need to decide which restrictor / prolongator to use based on the provided weights.

## Next steps
1. Implement the new classes for restriction and prolongation as helpers in `grid_operators.py`. 
2. Refactor the `SubdomainProjection` to use the new classes. This will entail deciding which indices to use based on input tot the methods `cell_prolongation()` etc. Note that for the `SubdomainProjection`, the weights will always be unitary.
3. Introduce tests of the new classes.
4. Do benchmarking to compare performance with the existing implementation.
5. Start thinking of the `MortarProjection`

**Comment by keileg** [comment]
Update, finally: Projections from mortar to secondary cannot use the slicing trick straight away, since even for conforming grids, this is a mapping from two mortar cells to one a single lower-dimensional cell. In retrospect, this is fairly obvious.

In the conforming case, it could be possible to do some clever tricks with indices that exploit that there is a 2-1 correspondence between mortar and secondary grids (as opposed to some-some for non-conforming grids). However, the benefit of doing this is unclear, while the cost measured in development time and code complexity may be substantial. 

For now, the goal of the project is therefore to roll out the slicing projections for subdomains, and for mapping of mortars to primary *in the conforming case*. Mapping from mortar to secondary will stay in matrix form, as will all mortar mappings for non-conforming grids. However, we will also change the implementation so that the projection matrices are created on demand, rather than at initialization (this should cut a substantial part of the computational cost).

**Comment by keileg** [comment]
This issue was partly solved by #1301. Move to backlog, awaiting #1181.

**Comment by keileg** [comment]
This will be picked up again quite soon. Below is a list of functions where the new functionality should be considered introduced:

- [ ] TangentialNormalProjection, methods project_normal, project_tangential
- [ ] Model geometry, methods e_i and basis
