### ISSUE TITLE
Integrate TPSA into the multiphysics models

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1231]
This issue coordinates the tasks needed to integrate the newly developed TPSA discretization into the models.

```[tasklist]
### Tasks
- [ ] Extract constitutive laws for the mechanics rotation formulation
- [ ] Define an extended constitutive law that introduce Cosserat materials
- [ ] Mixin for rotation and total pressure variables
- [ ] Boundary conditions for rotation variables (only to be used in the Cosserat setting)
- [ ] Conservation equations for angular momentum and solid mass
- [ ] Modification of constitutive laws for poro- and thermoporomechanics
- [ ] Define variable names ( `rotation,` `total_pressure`) and physics keywords (`rotation`). This will require `__init__` functions, or some rewrite of the existing models.
- [ ] Define a single mixin that can be used to augment an existing (thermo/poro)-mechanics models with a three-field mechanics formulation.
- [ ] Define an additional (single) mixin that adds the Cosserat material parameters to a model that already uses a three-field mechanics formulation.
- [ ] Devise a strategy for testing. 
```

**Comment by keileg** [comment]
This is put on hold pending clarifications on details in the model formulation.

**Comment by keileg** [comment]
This was completed in #1485
