### ISSUE TITLE
Refactor mono-dimensional FV tests

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#958]
```[tasklist]
### Tasks
- [x] unit.test_mpsa.py
- [x] unit.test_mpfa_gravity.py
- [x] integration/test_mpfa.py
- [x] integration/test_mpsa.py
- [x] unit/test_fv_disc.py
- [x] integration/test_fv_disc.py
```

**Comment by keileg** [comment]
From a quick glance, my understanding of these tests are:
* unit/test_fv_disc, unit/test_mpfa, integration/test_fv_disc all verify that mpfa/tpfa produce expected stencils on simple geometries. We probably want to keep some of these, but maybe not all (and there could be real duplicates among the tests)
* unit.test_mpsa and integration/test_mpsa do something similar for mpsa.
* test_mpfa_mpsa_convergence is a convergence test for various configurations. I'm not sure if we want to keep these: For mpfa, we partly cover this also in the single_phase_flow convergence test; hopefully we will have something similar for mpsa in the not too distant future. Note that test_mpfa_mpsa_convergence also consider heterogeneous materials, which is a much more powerful test than the homogeneous materials considered elsewhere. Could skipping be an option? Not sure.
* test_mpfa_gravity: Is a stand-alone test. This I think we want to keep.

**Comment by IvarStefansson** [comment]
Keeping this open as we decided to postpone the convergence test.
