### ISSUE TITLE
Refactor mono-dimensional FE tests

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#959]
```[tasklist]
### Tasks
- [ ] unit.test_hybrid_vem.
- [ ] unit.test_dual_vem.py
- [ ] unit.test_rt0.py
- [ ] unit.test_mass_matrix.py
```
