### ISSUE TITLE
Refactor tests of geometry computations

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#962]
Tests for pp.geometry
```[tasklist]
### Tasks
- [x] unit/test_distance_computations.py
- [x] unit/test_inside_polygon.py
- [x] unit/test_is_point_in_cell.py
- [x] unit/test_map_geometry.py
- [x] unit/test_match_triangles.py
- [x] unit/test_point_geometry_computations.py
- [x] unit/test_snap_points_to_lines.py
- [x] unit/test_ccw.py
- [x] unit/test_adtree.py
```
