### ISSUE TITLE
Refactor fracture network tests

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#963]
```[tasklist]
### Tasks
- [x] unit/test_fracture_class.py
- [x] unit/test_fracture_importer.py
- [x] unit/test_fracture_intersection.py (partly belongs to #962)
- [x] unit/test_fracture_network.py
- [x] unit/test_fracture_utils.py
```
