### ISSUE TITLE
Consider tests for deletion

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#967]
```[tasklist]
### Tasks
- [x] integration/test_DFN.py
- [x] unit/test_darcy_mortar.py
- [x] unit/test_assembler.py
- [x] unit/test_merging_non_conforming_grids.py
- [x] unit/test_dof_manager.py
- [x] unit/test_source.py
- [x] integration/test_vem_convergence.py  (relies on the assembler)
- [x] integration/test_grid_factory.py
- [ ] __
- [ ] unit/test_error_computation.py
- [ ] integration/test_coarsening.py
- [x] integration/test_TpfaMonoCoupling.py
- [ ] integration/test_mpfaMultiDim.py
- [x] integration/test_tpfaMultiDim.py
- [x] integration/test_darcy_mortar_immersed_fracture.py
```

**Comment by keileg** [comment]
We may not delete these tests directly in the upcoming refactoring, but we should make a decision either to keep them (and move to the appropriate refactoring issue), or mark them for execution together with any relevant code in the source.

**Comment by keileg** [comment]
mixed_dim_gravity relies on the assembler, so it probably has to go. This will leave a hole in the test coverage of a potentially complex and important detail, though, so we should think twice about this one.

**Comment by keileg** [comment]
Will be handled in #1066
