### ISSUE TITLE
Refactor tests for grid generation

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#969]
```[tasklist]
### Tasks
- [x] integration/test_mdg_generation.py
- [x] unit/test_grid_refinement.py
- [x] unit/test_grid_extrusion.py
```
