### ISSUE TITLE
Refactor tests for minor utility functions

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#973]
```[tasklist]
### Tasks
- [x] unit/test_mcolon.py
- [x] unit/test_permutations.py
- [ ] unit/test_setmembership.py
- [x] unit/test_graph.py
- [x] unit/test_half_space.py
- [x] unit/test_sort_points.py
```

**Comment by vlipovac** [comment]
@keileg  Is `unit/test_half_space` certainly a utility function? Compared to the other files it relies on `pp.geometry` not `pp.utils`
