### ISSUE TITLE
Refactor tests of ad framework

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#977]
```[tasklist]
### Tasks
- [ ] unit/ad/test_ad_array_forward_mode.py
- [ ] unit/ad/test_ad_operator_tree.py
- [ ] unit/ad/test_forward_ad_standard_functions.py
- [ ] unit/ad/test_grid_operators.py
- [ ] integration/test_ad.py
```
