### ISSUE TITLE
Refactor models tests

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#978]
```[tasklist]
### Tasks
- [ ] integration/models/test_ad_methods_single_phase_flow.py
- [ ] integration/models/test_constitutive_laws.py
- [ ] integration/models/test_diagnostics_mixin.py
- [ ] integration/models/test_energy_balance.py
- [ ] integration/models/test_equations.py
- [ ] integration/models/test_evaluate_constitutive_laws.py
- [ ] integration/models/test_geometry.py
- [ ] integration/models/test_mass_balance.py
- [ ] integration/models/test_materials_and_units.py
- [ ] integration/models/test_momentum_balance.py
- [ ] integration/models/test_poromechanics.py
- [ ] integration/models/test_rediscretization.py
- [ ] integration/models/test_restart.py
- [ ] integration/models/test_thermoporomechanics.py
- [ ] integration/models/test_variables.py
- [ ] integration/models/test_well_models.py
```
