### ISSUE TITLE
Refactor tests relating to intersection detection

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#985]
```[tasklist]
### Tasks
- [x] unit/test_intersections.py
- [x] unit/test_polygon_intersection.py
- [x] unit/test_fracture_intersection.py (partly belongs to #963)
- [x] unit/test_segment_intersection_3d.py
```
